kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: airflow-cluster
nodes:
  - role: control-plane
  - role: worker
    extraMounts:
      - hostPath: ./dags
        containerPath: /opt/airflow/dags
      - hostPath: ./plugins
        containerPath: /opt/airflow/plugins
