apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  labels:
    app: elasticsearch
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: "/usr/share/elasticsearch/data"
