prometheus:
  prometheusSpec:
    additionalScrapeConfigs: |
      - job_name: "statsd-exporter"
        static_configs:
          - targets:
              - airflow-statsd:9102
        tls_config:
          insecure_skip_verify: true
grafana:
  defaultDashboardsEnabled: false
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          folder: ""
          type: file
          options:
            path: /var/lib/grafana/dashboards/default
  dashboardsConfigMaps:
    default: "grafana-dashboards"
nodeExporter:
  enabled: false
alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: false
